# Github will automatically rewrite safe to be true.
# By setting it to false, we fake a development/production flag. For example,
# now we can check site.safe before we render analytics.
safe: false

# Syntax highlighter
highlighter: rouge

# Use collections to create subpages for recipes, etc.
collections:
  recipes:
    output: true
    permalink: '/:collection/:path/'
